display a human readable version of the default expiry time
rixx/abbr pull request #13
Opened 2016-10-18 15:59 UTC by nazco

2016-10-18 20:38 UTC, rixx requested changes
Thank you for the PR! Please review my comments and see if you want to update the PR. Otherwise I'll merge it and continue to work on it myself.

2016-10-18 20:38 UTC, rixx commented on abbr/views.py
> +from ago import human
In Python, third-party libraries commonly go below standard library imports and above local imports.

2016-10-18 20:38 UTC, rixx commented on abbr/views.py
> +        {'name': 'default expiry (' + human(get_expiry(), precision=1) + ")", 'value': from_datetime(get_expiry()) },
It might be better to use the human() method on all fields here, for consistency.

2016-10-18 20:38 UTC, rixx commented on abbr/views.py
> +                       "('%Y-%m-%d %H:%M:%S', Default: " + human(get_expiry(), precision=1) + ").")
Since we return the format here, I think the message would look strange with a humanized value and be more consistent when using an ISO-ish date.

2016-10-18 20:38 UTC, rixx commented on abbr/utils.py
> +    return datetime.now() + app.config.get('EXPIRY') + timedelta(seconds=1)
I'm not really happy with this. I'd prefer to either find a library that is capable of rounding up or adding the second for display purposes only.

In the second case, the method `get_expiry` could return a tuple of a time and a description.

2016-10-20 20:30 UTC, nazco commented
I tried to address all your comments in the new commits

2016-10-21 21:29 UTC, rixx approved these changes

2016-10-21 21:30 UTC, merged